WARNING 2015-03-10 10:24:56,263 base 31399 140644588652288 Not Found: /dprr/
ERROR 2015-03-10 10:30:37,390 base 31767 140152334350080 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 343, in resolve
    for pattern in self.url_patterns:
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 372, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/vagrant/dprr/urls.py", line 23, in <module>
    url(r'^$', views.index, name='index'),
NameError: name 'views' is not defined
ERROR 2015-03-10 10:30:37,665 base 31767 140152334350080 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 343, in resolve
    for pattern in self.url_patterns:
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 372, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/vagrant/dprr/urls.py", line 23, in <module>
    url(r'^$', views.index, name='index'),
NameError: name 'views' is not defined
ERROR 2015-03-10 10:31:13,471 base 31767 140152334350080 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 343, in resolve
    for pattern in self.url_patterns:
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 372, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/vagrant/dprr/urls.py", line 23, in <module>
    url(r'^$', views.index, name='index'),
NameError: name 'views' is not defined
ERROR 2015-03-10 10:31:14,949 base 31767 140152334350080 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 343, in resolve
    for pattern in self.url_patterns:
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 372, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/vagrant/dprr/urls.py", line 23, in <module>
    url(r'^$', views.index, name='index'),
NameError: name 'views' is not defined
ERROR 2015-03-10 10:31:17,580 base 31767 140152334350080 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 343, in resolve
    for pattern in self.url_patterns:
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 372, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/vagrant/dprr/urls.py", line 23, in <module>
    url(r'^$', views.index, name='index'),
NameError: name 'views' is not defined
ERROR 2015-03-10 10:31:43,120 base 31767 140152334350080 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 343, in resolve
    for pattern in self.url_patterns:
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 372, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/vagrant/dprr/urls.py", line 23, in <module>
    url(r'^$', views.index, name='index'),
NameError: name 'views' is not defined
ERROR 2015-03-10 10:32:46,223 base 31767 140152334350080 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 2, in index
    return render_to_response('base.html')
NameError: global name 'render_to_response' is not defined
ERROR 2015-03-10 10:33:31,621 base 31806 140510077126400 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 2, in index
    return render_to_response('base.html')
NameError: global name 'render_to_response' is not defined
ERROR 2015-03-10 10:33:32,837 base 31806 140510077126400 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 2, in index
    return render_to_response('base.html')
NameError: global name 'render_to_response' is not defined
ERROR 2015-03-10 10:34:20,642 base 31817 140117375661824 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 170, in render_to_string
    t = get_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 162, in compile_string
    return parser.parse()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 290, in parse
    compiled_result = compile_func(self, token)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 1119, in load
    (taglib, e))
TemplateSyntaxError: 'compress' is not a valid tag library: Template library compress not found, tried django.templatetags.compress,grappelli.templatetags.compress,django.contrib.admin.templatetags.compress,django.contrib.staticfiles.templatetags.compress,mptt.templatetags.compress,django_extensions.templatetags.compress
ERROR 2015-03-10 10:35:12,920 base 31817 140117375661824 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 170, in render_to_string
    t = get_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 162, in compile_string
    return parser.parse()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 288, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 344, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'static'
ERROR 2015-03-10 10:35:36,582 base 31817 140117375661824 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 170, in render_to_string
    t = get_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 162, in compile_string
    return parser.parse()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 288, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 344, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'static'
ERROR 2015-03-10 10:36:53,832 base 31835 140578505312000 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 170, in render_to_string
    t = get_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 162, in compile_string
    return parser.parse()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 288, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 344, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'static'
ERROR 2015-03-10 10:37:17,233 base 31844 139713608414976 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 170, in render_to_string
    t = get_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 162, in compile_string
    return parser.parse()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 288, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 344, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'static'
ERROR 2015-03-10 10:37:18,513 base 31844 139713608414976 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 170, in render_to_string
    t = get_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 162, in compile_string
    return parser.parse()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 288, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 344, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'static'
ERROR 2015-03-10 10:37:55,334 base 31844 139713608414976 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 170, in render_to_string
    t = get_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 162, in compile_string
    return parser.parse()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 288, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 344, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'static'
WARNING 2015-03-10 10:38:16,615 base 31844 139713608414976 Not Found: /assets/vendor/modernizr/modernizr.js
WARNING 2015-03-10 10:38:16,635 base 31844 139713600022272 Not Found: /assets/vendor/jquery/dist/jquery.min.js
WARNING 2015-03-10 10:38:16,634 base 31844 139713591629568 Not Found: /assets/vendor/foundation/js/foundation.min.js
WARNING 2015-03-10 10:38:16,643 base 31844 139713583236864 Not Found: /assets/javascripts/config.js
WARNING 2015-03-10 10:38:16,696 base 31844 139713591629568 Not Found: /assets/javascripts/config.js
ERROR 2015-03-10 10:41:02,246 base 31889 140206382335744 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 170, in render_to_string
    t = get_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 162, in compile_string
    return parser.parse()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 288, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 344, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'compress'
ERROR 2015-03-10 10:41:29,851 base 31889 140206382335744 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 170, in render_to_string
    t = get_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 162, in compile_string
    return parser.parse()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 288, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 344, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'compress'
ERROR 2015-03-10 10:41:31,043 base 31889 140206382335744 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 170, in render_to_string
    t = get_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 162, in compile_string
    return parser.parse()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 288, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 344, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'compress'
ERROR 2015-03-10 10:41:59,957 base 31889 140206382335744 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 170, in render_to_string
    t = get_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 162, in compile_string
    return parser.parse()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 288, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 344, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'compress'
ERROR 2015-03-10 10:42:01,833 base 31889 140206382335744 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 170, in render_to_string
    t = get_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 162, in compile_string
    return parser.parse()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 288, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 344, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'compress'
ERROR 2015-03-10 10:56:04,478 base 32003 140184669341440 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 170, in render_to_string
    t = get_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 162, in compile_string
    return parser.parse()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 288, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 344, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'compress'
ERROR 2015-03-10 10:56:05,943 base 32003 140184669341440 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 170, in render_to_string
    t = get_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 162, in compile_string
    return parser.parse()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 288, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 344, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'compress'
ERROR 2015-03-10 11:04:18,637 base 32054 140643188840192 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 87, in get_response
    response = middleware_method(request)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/wagtail/wagtailcore/middleware.py", line 11, in process_request
    request.site = Site.find_for_request(request)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/wagtail/wagtailcore/models.py", line 78, in find_for_request
    return Site.objects.get(hostname=hostname)  # Site.DoesNotExist here goes to the final except clause
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 351, in get
    num = len(clone)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 122, in __len__
    self._fetch_all()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 700, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: relation "wagtailcore_site" does not exist
LINE 1: ...ge_id", "wagtailcore_site"."is_default_site" FROM "wagtailco...
                                                             ^

ERROR 2015-03-10 11:04:56,710 base 32065 140413127112448 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 87, in get_response
    response = middleware_method(request)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/wagtail/wagtailcore/middleware.py", line 11, in process_request
    request.site = Site.find_for_request(request)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/wagtail/wagtailcore/models.py", line 78, in find_for_request
    return Site.objects.get(hostname=hostname)  # Site.DoesNotExist here goes to the final except clause
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 351, in get
    num = len(clone)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 122, in __len__
    self._fetch_all()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 700, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: relation "wagtailcore_site" does not exist
LINE 1: ...ge_id", "wagtailcore_site"."is_default_site" FROM "wagtailco...
                                                             ^

ERROR 2015-03-10 11:05:46,017 base 32092 139854729742080 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 87, in get_response
    response = middleware_method(request)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/wagtail/wagtailcore/middleware.py", line 11, in process_request
    request.site = Site.find_for_request(request)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/wagtail/wagtailcore/models.py", line 78, in find_for_request
    return Site.objects.get(hostname=hostname)  # Site.DoesNotExist here goes to the final except clause
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 351, in get
    num = len(clone)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 122, in __len__
    self._fetch_all()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 700, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: relation "wagtailcore_site" does not exist
LINE 1: ...ge_id", "wagtailcore_site"."is_default_site" FROM "wagtailco...
                                                             ^

ERROR 2015-03-10 11:05:47,824 base 32092 139854729742080 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 87, in get_response
    response = middleware_method(request)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/wagtail/wagtailcore/middleware.py", line 11, in process_request
    request.site = Site.find_for_request(request)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/wagtail/wagtailcore/models.py", line 78, in find_for_request
    return Site.objects.get(hostname=hostname)  # Site.DoesNotExist here goes to the final except clause
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 351, in get
    num = len(clone)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 122, in __len__
    self._fetch_all()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 700, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: relation "wagtailcore_site" does not exist
LINE 1: ...ge_id", "wagtailcore_site"."is_default_site" FROM "wagtailco...
                                                             ^

ERROR 2015-03-10 11:10:30,180 base 32111 139929991026432 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 87, in get_response
    response = middleware_method(request)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/wagtail/wagtailcore/middleware.py", line 11, in process_request
    request.site = Site.find_for_request(request)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/wagtail/wagtailcore/models.py", line 78, in find_for_request
    return Site.objects.get(hostname=hostname)  # Site.DoesNotExist here goes to the final except clause
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 351, in get
    num = len(clone)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 122, in __len__
    self._fetch_all()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 700, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: relation "wagtailcore_site" does not exist
LINE 1: ...ge_id", "wagtailcore_site"."is_default_site" FROM "wagtailco...
                                                             ^

ERROR 2015-03-10 11:10:31,372 base 32111 139929991026432 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 87, in get_response
    response = middleware_method(request)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/wagtail/wagtailcore/middleware.py", line 11, in process_request
    request.site = Site.find_for_request(request)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/wagtail/wagtailcore/models.py", line 78, in find_for_request
    return Site.objects.get(hostname=hostname)  # Site.DoesNotExist here goes to the final except clause
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 351, in get
    num = len(clone)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 122, in __len__
    self._fetch_all()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 700, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: relation "wagtailcore_site" does not exist
LINE 1: ...ge_id", "wagtailcore_site"."is_default_site" FROM "wagtailco...
                                                             ^

ERROR 2015-03-10 11:10:32,481 base 32111 139929991026432 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 87, in get_response
    response = middleware_method(request)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/wagtail/wagtailcore/middleware.py", line 11, in process_request
    request.site = Site.find_for_request(request)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/wagtail/wagtailcore/models.py", line 78, in find_for_request
    return Site.objects.get(hostname=hostname)  # Site.DoesNotExist here goes to the final except clause
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 351, in get
    num = len(clone)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 122, in __len__
    self._fetch_all()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 700, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: relation "wagtailcore_site" does not exist
LINE 1: ...ge_id", "wagtailcore_site"."is_default_site" FROM "wagtailco...
                                                             ^

ERROR 2015-03-10 11:11:24,454 base 32172 140044105008896 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 343, in resolve
    for pattern in self.url_patterns:
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 372, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/vagrant/dprr/urls.py", line 40, in <module>
    url(r'^wagtail/images/', include(wagtailimages_urls)),
NameError: name 'wagtailimages_urls' is not defined
ERROR 2015-03-10 11:11:42,932 base 32172 140044105008896 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 343, in resolve
    for pattern in self.url_patterns:
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 372, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/vagrant/dprr/urls.py", line 41, in <module>
    url(r'^wagtail/embeds/', include(wagtailembeds_urls)),
NameError: name 'wagtailembeds_urls' is not defined
ERROR 2015-03-10 11:11:56,949 base 32172 140044105008896 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 170, in render_to_string
    t = get_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 162, in compile_string
    return parser.parse()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 288, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 344, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'compress'
ERROR 2015-03-10 11:22:49,935 base 32386 139782700435200 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 170, in render_to_string
    t = get_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 162, in compile_string
    return parser.parse()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 288, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 344, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'compress'
ERROR 2015-03-10 11:29:11,070 base 32430 139949160527616 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 170, in render_to_string
    t = get_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 162, in compile_string
    return parser.parse()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 288, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 344, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'compress'
ERROR 2015-03-10 11:29:12,513 base 32430 139949160527616 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 170, in render_to_string
    t = get_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 162, in compile_string
    return parser.parse()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 288, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 344, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'compress'
ERROR 2015-03-10 11:29:59,869 base 32460 140662277641984 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 170, in render_to_string
    t = get_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 162, in compile_string
    return parser.parse()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 288, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 344, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'compress'
ERROR 2015-03-10 11:35:09,102 base 32460 140662277641984 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 172, in render_to_string
    return t.render(Context(dictionary))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 149, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 108, in render_compressed
    rendered_output = self.render_output(compressor, mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 121, in render_output
    return compressor.output(mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 46, in output
    self.split_contents()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 22, in split_contents
    basename = self.get_basename(elem_attribs['href'])
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 86, in get_basename
    "compressed" % (url, base_url))
UncompressableFileError: '/assets/scss/app.scss' isn't accessible via COMPRESS_URL ('/static/') and can't be compressed
ERROR 2015-03-10 11:38:40,837 base 32460 140662277641984 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 172, in render_to_string
    return t.render(Context(dictionary))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 149, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 108, in render_compressed
    rendered_output = self.render_output(compressor, mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 121, in render_output
    return compressor.output(mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 46, in output
    self.split_contents()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 22, in split_contents
    basename = self.get_basename(elem_attribs['href'])
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 86, in get_basename
    "compressed" % (url, base_url))
UncompressableFileError: '/assets/scss/app.scss' isn't accessible via COMPRESS_URL ('/static/') and can't be compressed
ERROR 2015-03-10 11:38:42,316 base 32460 140662277641984 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 172, in render_to_string
    return t.render(Context(dictionary))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 149, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 108, in render_compressed
    rendered_output = self.render_output(compressor, mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 121, in render_output
    return compressor.output(mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 46, in output
    self.split_contents()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 22, in split_contents
    basename = self.get_basename(elem_attribs['href'])
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 86, in get_basename
    "compressed" % (url, base_url))
UncompressableFileError: '/assets/scss/app.scss' isn't accessible via COMPRESS_URL ('/static/') and can't be compressed
ERROR 2015-03-10 11:43:05,220 base 32548 140040294364928 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 172, in render_to_string
    return t.render(Context(dictionary))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 149, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 108, in render_compressed
    rendered_output = self.render_output(compressor, mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 121, in render_output
    return compressor.output(mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 46, in output
    self.split_contents()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 23, in split_contents
    filename = self.get_filename(basename)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 137, in get_filename
    self.finders and " or with staticfiles." or "."))
UncompressableFileError: 'scss/main.scss' could not be found in the COMPRESS_ROOT '/vagrant/static' or with staticfiles.
WARNING 2015-03-10 11:44:34,834 base 32548 140040246036224 Not Found: /assets/images/favicon.ico
WARNING 2015-03-10 11:44:34,870 base 32548 140040254428928 Not Found: /assets/javascripts/config.js
WARNING 2015-03-10 11:44:34,870 base 32548 140040271214336 Not Found: /assets/vendor/jquery/dist/jquery.min.js
WARNING 2015-03-10 11:44:34,873 base 32548 140040262821632 Not Found: /assets/vendor/foundation/js/foundation.min.js
WARNING 2015-03-10 11:44:34,875 base 32548 140040279607040 Not Found: /assets/vendor/modernizr/modernizr.js
WARNING 2015-03-10 11:44:35,015 base 32548 140040279607040 Not Found: /assets/vendor/jquery/dist/jquery.min.js
WARNING 2015-03-10 11:44:35,059 base 32548 140040279607040 Not Found: /assets/vendor/foundation/js/foundation.min.js
WARNING 2015-03-10 11:44:35,110 base 32548 140040254428928 Not Found: /assets/javascripts/config.js
ERROR 2015-03-10 11:47:19,749 base 32548 140040254428928 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 172, in render_to_string
    return t.render(Context(dictionary))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 149, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 108, in render_compressed
    rendered_output = self.render_output(compressor, mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 121, in render_output
    return compressor.output(mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 51, in output
    ret.append(subnode.output(*args, **kwargs))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 53, in output
    return super(CssCompressor, self).output(*args, **kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 285, in output
    output = '\n'.join(self.filter_input(forced))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 224, in filter_input
    for hunk in self.hunks(forced):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 200, in hunks
    precompiled, value = self.precompile(value, **options)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 264, in precompile
    return True, filter.input(**kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django_libsass.py", line 51, in input
    return compile(filename=self.filename)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django_libsass.py", line 41, in compile
    return sass.compile(**kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/sass.py", line 299, in compile
    raise CompileError(v)
CompileError: /vagrant/assets/vendor/foundation/scss/foundation/functions:13: error: error reading values after $modules

ERROR 2015-03-10 11:48:35,950 base 32548 140040254428928 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 172, in render_to_string
    return t.render(Context(dictionary))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 149, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 108, in render_compressed
    rendered_output = self.render_output(compressor, mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 121, in render_output
    return compressor.output(mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 51, in output
    ret.append(subnode.output(*args, **kwargs))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 53, in output
    return super(CssCompressor, self).output(*args, **kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 285, in output
    output = '\n'.join(self.filter_input(forced))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 224, in filter_input
    for hunk in self.hunks(forced):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 200, in hunks
    precompiled, value = self.precompile(value, **options)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 264, in precompile
    return True, filter.input(**kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django_libsass.py", line 51, in input
    return compile(filename=self.filename)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django_libsass.py", line 41, in compile
    return sass.compile(**kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/sass.py", line 299, in compile
    raise CompileError(v)
CompileError: /vagrant/assets/vendor/foundation/scss/foundation/settings:58: error: file to import not found or unreadable: "foundation/functions"

ERROR 2015-03-10 11:48:56,823 base 32548 140040254428928 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 172, in render_to_string
    return t.render(Context(dictionary))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 149, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 108, in render_compressed
    rendered_output = self.render_output(compressor, mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 121, in render_output
    return compressor.output(mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 51, in output
    ret.append(subnode.output(*args, **kwargs))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 53, in output
    return super(CssCompressor, self).output(*args, **kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 285, in output
    output = '\n'.join(self.filter_input(forced))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 224, in filter_input
    for hunk in self.hunks(forced):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 200, in hunks
    precompiled, value = self.precompile(value, **options)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 264, in precompile
    return True, filter.input(**kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django_libsass.py", line 51, in input
    return compile(filename=self.filename)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django_libsass.py", line 41, in compile
    return sass.compile(**kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/sass.py", line 299, in compile
    raise CompileError(v)
CompileError: /vagrant/assets/vendor/foundation/scss/foundation/settings:58: error: file to import not found or unreadable: "foundation/functions"

ERROR 2015-03-10 11:48:58,573 base 32548 140040254428928 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 172, in render_to_string
    return t.render(Context(dictionary))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 149, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 108, in render_compressed
    rendered_output = self.render_output(compressor, mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 121, in render_output
    return compressor.output(mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 51, in output
    ret.append(subnode.output(*args, **kwargs))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 53, in output
    return super(CssCompressor, self).output(*args, **kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 285, in output
    output = '\n'.join(self.filter_input(forced))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 224, in filter_input
    for hunk in self.hunks(forced):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 200, in hunks
    precompiled, value = self.precompile(value, **options)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 264, in precompile
    return True, filter.input(**kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django_libsass.py", line 51, in input
    return compile(filename=self.filename)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django_libsass.py", line 41, in compile
    return sass.compile(**kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/sass.py", line 299, in compile
    raise CompileError(v)
CompileError: /vagrant/assets/vendor/foundation/scss/foundation/settings:58: error: file to import not found or unreadable: "foundation/functions"

ERROR 2015-03-10 12:09:59,735 base 32548 140040254428928 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 172, in render_to_string
    return t.render(Context(dictionary))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 149, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 108, in render_compressed
    rendered_output = self.render_output(compressor, mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 121, in render_output
    return compressor.output(mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 51, in output
    ret.append(subnode.output(*args, **kwargs))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 53, in output
    return super(CssCompressor, self).output(*args, **kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 285, in output
    output = '\n'.join(self.filter_input(forced))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 224, in filter_input
    for hunk in self.hunks(forced):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 200, in hunks
    precompiled, value = self.precompile(value, **options)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 264, in precompile
    return True, filter.input(**kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django_libsass.py", line 51, in input
    return compile(filename=self.filename)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django_libsass.py", line 41, in compile
    return sass.compile(**kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/sass.py", line 299, in compile
    raise CompileError(v)
CompileError: /vagrant/assets/scss/settings:58: error: file to import not found or unreadable: "../vendor/foundadion/scss/foundation/functions"

ERROR 2015-03-10 12:11:30,579 base 32548 140040254428928 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 172, in render_to_string
    return t.render(Context(dictionary))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 149, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 108, in render_compressed
    rendered_output = self.render_output(compressor, mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 121, in render_output
    return compressor.output(mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 51, in output
    ret.append(subnode.output(*args, **kwargs))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 53, in output
    return super(CssCompressor, self).output(*args, **kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 285, in output
    output = '\n'.join(self.filter_input(forced))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 224, in filter_input
    for hunk in self.hunks(forced):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 200, in hunks
    precompiled, value = self.precompile(value, **options)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 264, in precompile
    return True, filter.input(**kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django_libsass.py", line 51, in input
    return compile(filename=self.filename)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django_libsass.py", line 41, in compile
    return sass.compile(**kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/sass.py", line 299, in compile
    raise CompileError(v)
CompileError: /vagrant/assets/scss/settings:58: error: file to import not found or unreadable: "../vendor/foundadion/scss/foundation/functions"

ERROR 2015-03-10 12:11:32,175 base 32548 140040254428928 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 172, in render_to_string
    return t.render(Context(dictionary))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 149, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 108, in render_compressed
    rendered_output = self.render_output(compressor, mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 121, in render_output
    return compressor.output(mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 51, in output
    ret.append(subnode.output(*args, **kwargs))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 53, in output
    return super(CssCompressor, self).output(*args, **kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 285, in output
    output = '\n'.join(self.filter_input(forced))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 224, in filter_input
    for hunk in self.hunks(forced):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 200, in hunks
    precompiled, value = self.precompile(value, **options)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 264, in precompile
    return True, filter.input(**kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django_libsass.py", line 51, in input
    return compile(filename=self.filename)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django_libsass.py", line 41, in compile
    return sass.compile(**kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/sass.py", line 299, in compile
    raise CompileError(v)
CompileError: /vagrant/assets/scss/settings:58: error: file to import not found or unreadable: "../vendor/foundadion/scss/foundation/functions"

ERROR 2015-03-10 12:12:00,775 base 32548 140040254428928 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 172, in render_to_string
    return t.render(Context(dictionary))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 149, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 108, in render_compressed
    rendered_output = self.render_output(compressor, mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 121, in render_output
    return compressor.output(mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 51, in output
    ret.append(subnode.output(*args, **kwargs))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 53, in output
    return super(CssCompressor, self).output(*args, **kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 285, in output
    output = '\n'.join(self.filter_input(forced))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 224, in filter_input
    for hunk in self.hunks(forced):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 200, in hunks
    precompiled, value = self.precompile(value, **options)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 264, in precompile
    return True, filter.input(**kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django_libsass.py", line 51, in input
    return compile(filename=self.filename)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django_libsass.py", line 41, in compile
    return sass.compile(**kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/sass.py", line 299, in compile
    raise CompileError(v)
CompileError: /vagrant/assets/scss/settings:58: error: file to import not found or unreadable: "vendor/foundadion/scss/foundation/functions"

ERROR 2015-03-10 12:12:26,556 base 32548 140040254428928 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 172, in render_to_string
    return t.render(Context(dictionary))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 149, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 108, in render_compressed
    rendered_output = self.render_output(compressor, mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 121, in render_output
    return compressor.output(mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 51, in output
    ret.append(subnode.output(*args, **kwargs))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 53, in output
    return super(CssCompressor, self).output(*args, **kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 285, in output
    output = '\n'.join(self.filter_input(forced))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 224, in filter_input
    for hunk in self.hunks(forced):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 200, in hunks
    precompiled, value = self.precompile(value, **options)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 264, in precompile
    return True, filter.input(**kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django_libsass.py", line 51, in input
    return compile(filename=self.filename)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django_libsass.py", line 41, in compile
    return sass.compile(**kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/sass.py", line 299, in compile
    raise CompileError(v)
CompileError: /vagrant/assets/scss/settings:58: error: file to import not found or unreadable: "/static/vendor/foundadion/scss/foundation/functions"

ERROR 2015-03-10 12:12:28,110 base 32548 140040254428928 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 172, in render_to_string
    return t.render(Context(dictionary))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 149, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 108, in render_compressed
    rendered_output = self.render_output(compressor, mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 121, in render_output
    return compressor.output(mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 51, in output
    ret.append(subnode.output(*args, **kwargs))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 53, in output
    return super(CssCompressor, self).output(*args, **kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 285, in output
    output = '\n'.join(self.filter_input(forced))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 224, in filter_input
    for hunk in self.hunks(forced):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 200, in hunks
    precompiled, value = self.precompile(value, **options)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 264, in precompile
    return True, filter.input(**kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django_libsass.py", line 51, in input
    return compile(filename=self.filename)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django_libsass.py", line 41, in compile
    return sass.compile(**kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/sass.py", line 299, in compile
    raise CompileError(v)
CompileError: /vagrant/assets/scss/settings:58: error: file to import not found or unreadable: "/static/vendor/foundadion/scss/foundation/functions"

ERROR 2015-03-10 12:13:04,664 base 32548 140040254428928 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 172, in render_to_string
    return t.render(Context(dictionary))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 149, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 108, in render_compressed
    rendered_output = self.render_output(compressor, mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 121, in render_output
    return compressor.output(mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 51, in output
    ret.append(subnode.output(*args, **kwargs))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 53, in output
    return super(CssCompressor, self).output(*args, **kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 285, in output
    output = '\n'.join(self.filter_input(forced))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 224, in filter_input
    for hunk in self.hunks(forced):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 200, in hunks
    precompiled, value = self.precompile(value, **options)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 264, in precompile
    return True, filter.input(**kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django_libsass.py", line 51, in input
    return compile(filename=self.filename)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django_libsass.py", line 41, in compile
    return sass.compile(**kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/sass.py", line 299, in compile
    raise CompileError(v)
CompileError: /vagrant/assets/scss/settings:58: error: file to import not found or unreadable: "/static/vendor/foundadion/scss/foundation/functions"

ERROR 2015-03-10 12:14:06,652 base 32548 140040254428928 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 172, in render_to_string
    return t.render(Context(dictionary))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 149, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 108, in render_compressed
    rendered_output = self.render_output(compressor, mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 121, in render_output
    return compressor.output(mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 51, in output
    ret.append(subnode.output(*args, **kwargs))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 53, in output
    return super(CssCompressor, self).output(*args, **kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 285, in output
    output = '\n'.join(self.filter_input(forced))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 224, in filter_input
    for hunk in self.hunks(forced):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 200, in hunks
    precompiled, value = self.precompile(value, **options)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 264, in precompile
    return True, filter.input(**kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django_libsass.py", line 51, in input
    return compile(filename=self.filename)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django_libsass.py", line 41, in compile
    return sass.compile(**kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/sass.py", line 299, in compile
    raise CompileError(v)
CompileError: /vagrant/assets/vendor/foundation/scss/foundation/settings:58: error: file to import not found or unreadable: "foundation/functions"

ERROR 2015-03-10 12:14:40,064 base 32548 140040254428928 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 172, in render_to_string
    return t.render(Context(dictionary))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 149, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 108, in render_compressed
    rendered_output = self.render_output(compressor, mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 121, in render_output
    return compressor.output(mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 51, in output
    ret.append(subnode.output(*args, **kwargs))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 53, in output
    return super(CssCompressor, self).output(*args, **kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 285, in output
    output = '\n'.join(self.filter_input(forced))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 224, in filter_input
    for hunk in self.hunks(forced):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 200, in hunks
    precompiled, value = self.precompile(value, **options)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 264, in precompile
    return True, filter.input(**kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django_libsass.py", line 51, in input
    return compile(filename=self.filename)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django_libsass.py", line 41, in compile
    return sass.compile(**kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/sass.py", line 299, in compile
    raise CompileError(v)
CompileError: /vagrant/assets/scss/settings:58: error: file to import not found or unreadable: "/static/vendor/foundation/scss/foundation/functions"

ERROR 2015-03-10 12:15:07,963 base 32548 140040254428928 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 172, in render_to_string
    return t.render(Context(dictionary))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 149, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 108, in render_compressed
    rendered_output = self.render_output(compressor, mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 121, in render_output
    return compressor.output(mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 51, in output
    ret.append(subnode.output(*args, **kwargs))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 53, in output
    return super(CssCompressor, self).output(*args, **kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 285, in output
    output = '\n'.join(self.filter_input(forced))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 224, in filter_input
    for hunk in self.hunks(forced):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 200, in hunks
    precompiled, value = self.precompile(value, **options)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 264, in precompile
    return True, filter.input(**kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django_libsass.py", line 51, in input
    return compile(filename=self.filename)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django_libsass.py", line 41, in compile
    return sass.compile(**kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/sass.py", line 299, in compile
    raise CompileError(v)
CompileError: /vagrant/assets/vendor/foundation/scss/foundation/functions:13: error: error reading values after $modules

ERROR 2015-03-10 12:16:57,317 base 32548 140040254428928 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 172, in render_to_string
    return t.render(Context(dictionary))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 149, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 108, in render_compressed
    rendered_output = self.render_output(compressor, mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 121, in render_output
    return compressor.output(mode, forced=forced)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 51, in output
    ret.append(subnode.output(*args, **kwargs))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/css.py", line 53, in output
    return super(CssCompressor, self).output(*args, **kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 285, in output
    output = '\n'.join(self.filter_input(forced))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 224, in filter_input
    for hunk in self.hunks(forced):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 200, in hunks
    precompiled, value = self.precompile(value, **options)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/compressor/base.py", line 264, in precompile
    return True, filter.input(**kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django_libsass.py", line 51, in input
    return compile(filename=self.filename)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django_libsass.py", line 41, in compile
    return sass.compile(**kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/sass.py", line 299, in compile
    raise CompileError(v)
CompileError: /vagrant/assets/vendor/foundation/scss/foundation/functions:18: error: error reading values after )

WARNING 2015-03-10 12:17:20,463 base 32548 140040279607040 Not Found: /assets/vendor/modernizr/modernizr.js
WARNING 2015-03-10 12:18:27,887 base 32548 140040279607040 Not Found: /assets/vendor/modernizr/modernizr.js
WARNING 2015-03-10 12:18:43,486 base 32548 140040279607040 Not Found: /assets/vendor/modernizr/modernizr.js
WARNING 2015-03-10 12:18:45,254 base 32548 140040262821632 Not Found: /assets/vendor/modernizr/modernizr.js
ERROR 2015-03-10 12:24:16,641 base 32548 140040262821632 Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/dprr/views.py", line 4, in index
    return render_to_response('base.html')
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 172, in render_to_string
    return t.render(Context(dictionary))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 142, in render
    template = get_template(template)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 136, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: include/header.html
WARNING 2015-03-10 12:24:50,418 base 32548 140040254428928 Not Found: /assets/vendor/modernizr/modernizr.js
WARNING 2015-03-10 12:25:41,529 base 32548 140040254428928 Not Found: /assets/vendor/modernizr/modernizr.js
WARNING 2015-03-10 12:29:33,416 base 32548 140040294364928 Not Found: /assets/vendor/modernizr/modernizr.js
WARNING 2015-03-10 12:36:41,736 base 32548 140040246036224 Not Found: /assets/vendor/modernizr/modernizr.js
WARNING 2015-03-10 12:37:25,864 base 32548 140040271214336 Not Found: /assets/vendor/modernizr/modernizr.js
WARNING 2015-03-10 12:38:00,785 base 32548 140040271214336 Not Found: /assets/vendor/modernizr/modernizr.js
